sudo: required
dist: xenial
language: python
services:
- docker
python:
- '3.7'
env:
- PATROWL_ENGINE=nmap ENGINE_PORT=5001
# - PATROWL_ENGINE=nessus ENGINE_PORT=5002
# - PATROWL_ENGINE=burp ENGINE_PORT=5003
- PATROWL_ENGINE=ssllabs ENGINE_PORT=5004
- PATROWL_ENGINE=arachni ENGINE_PORT=5005
- PATROWL_ENGINE=owl_dns ENGINE_PORT=5006
- PATROWL_ENGINE=virustotal ENGINE_PORT=5007
# - PATROWL_ENGINE=urlvoid ENGINE_PORT=5008
# - PATROWL_ENGINE=cortex ENGINE_PORT=5009
# - PATROWL_ENGINE=censys ENGINE_PORT=5010
# - PATROWL_ENGINE=owl_leaks ENGINE_PORT=5012
# - PATROWL_ENGINE=owl_code ENGINE_PORT=5013
# - PATROWL_ENGINE=sslscan ENGINE_PORT=5014
- PATROWL_ENGINE=openvas ENGINE_PORT=5016
- PATROWL_ENGINE=certstream ENGINE_PORT=5017
- PATROWL_ENGINE=eyewitness ENGINE_PORT=5018
# - PATROWL_ENGINE=owl_request ENGINE_PORT=5019
# - PATROWL_ENGINE=pastebin_monitor ENGINE_PORT=5020
- PATROWL_ENGINE=droopescan ENGINE_PORT=5021
- PATROWL_ENGINE=apivoid ENGINE_PORT=5022
- PATROWL_ENGINE=wpscan ENGINE_PORT=5023
before_install:
- cd engines
install:
- pip3 install -r $PATROWL_ENGINE/requirements.txt
- pip3 install requests>=2.22.0
script:
- gunicorn engine-$PATROWL_ENGINE:app -b 0.0.0.0:1$ENGINE_PORT --chdir $PATROWL_ENGINE > /dev/null &
- docker --version
- docker build --tag patrowl-$PATROWL_ENGINE $PATROWL_ENGINE
# - if [ $PATROWL_ENGINE = "cortex" ]; then docker-compose -f cortex/tests/patrowl-tests-cortex_docker_compose.yml up -d; sleep 60; fi
- docker run -d --rm -p $ENGINE_PORT:$ENGINE_PORT patrowl-$PATROWL_ENGINE
- docker ps -a
- pytest -s $PATROWL_ENGINE/tests/test_*.py
after_script:
- docker images
